name: Build images

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build
        run: ./build.sh
